services:
  ubuntu:
    build: ./
    tty: true
    networks:
      - dockernetwork
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock
    dns:
      - 127.0.0.1
      - 8.8.8.8
    privileged: true

networks:
  dockernetwork:
    driver: bridge
